SCREEN_WIDTH = 800 
SCREEN_HEIGHT = 600 
SCREEN_TITLE = "ShootOut"
SCALING = 1.0
MOVEMENT_SPEED = 5
HEART_SEPARATION = 30
BULLET_SPEED= 4

SPRITE_SCALING_PLAYER = 0.5
SPRITE_SCALING_LASER = 0.7

# Index of textures, first element faces left, second faces right
TEXTURE_LEFT = 0
TEXTURE_RIGHT = 1